name: Automated Trading Bot

on:
  schedule:
    # Run every 5 minutes during market hours (9:30 AM - 4:00 PM ET, Mon-Fri)
    # Note: GitHub Actions uses UTC time
    - cron: '*/5 13-21 * * 1-5'  # 9:30 AM - 5:00 PM ET (13:30 - 21:00 UTC)
  workflow_dispatch:  # Allow manual triggering for testing

jobs:
  trading:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run trading bot
      env:
        ALPACA_API_KEY: ${{ secrets.ALPACA_API_KEY }}
        ALPACA_SECRET_KEY: ${{ secrets.ALPACA_SECRET_KEY }}
      run: python trading_bot.py
    
    - name: Upload logs
      uses: actions/upload-artifact@v3
      if: always()  # Upload logs even if the trading bot fails
      with:
        name: trading-logs-${{ github.run_number }}
        path: trading_bot.log
        retention-days: 30